export enum MyRoutes {
  Root = '/',
  Welcome = 'welcome',
  Login = 'login',
  Register = 'register',
  Home = 'home',
  Profile = 'profile',
  Artists = 'artists',
  Songs = 'songs',
  Playlists = 'playlists',
  NotFound = '404',
  Forbidden = 'forbidden',
  Genres = 'genres',
  CreateArtist = 'create-artist',
  CreateSong = 'create-song',
  CreatePlaylist = 'create-playlist',
}
