export enum MyRoutes {
  Root = '/',
  Welcome = 'welcome',
  Login = 'login',
  Register = 'register',
  Home = 'home',
  Profile = 'profile',
  Admin = 'admin',
  Artists = 'artists',
  Songs = 'songs',
  Playlists = 'playlists',
  NotFound = '404',
  Forbidden = 'forbidden',
  Genre = 'genre',
}
